name: DR_AR_env
channels:
  - conda-forge
  - r
dependencies:
  - r-base=4.3.1  # Adjust this to your R version
  - r-abind=1.4-5
  - r-admisc=0.37
  - r-annotate=1.78.0
  - r-annotationdbi=1.62.2
  - r-annotationhub=3.8.0
  - r-anytime=0.3.9
  - r-ape=5.8
  - r-aplot=0.2.2
  - r-argparse=2.2.2
  - r-arrow=13.0.0.1
  - r-asioheaders=1.22.1-2
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-aucell=1.22.0
  - r-babelgene=22.9
  - r-backports=1.4.1
  - r-base64enc=0.1-3
  - r-basilisk=1.12.1
  - r-basilisk.utils=1.12.1
  - r-batchelor=1.18.1
  - r-bayestestr=0.14.0
  - r-beachmat=2.16.0
  - r-beeswarm=0.4.0
  - r-bh=1.81.0-1
  - r-biglm=0.9-3
  - r-binman=0.1.3
  - r-biobase=2.60.0
  - r-biocfilecache=2.8.0
  - r-biocgenerics=0.46.0
  - r-biocio=1.10.0
  - r-biocmanager=1.30.21.1
  - r-biocneighbors=1.18.0
  - r-biocparallel=1.34.2
  - r-biocsingular=1.16.0
  - r-biocversion=3.17.1
  - r-biocviews=1.68.2
  - r-biomart=2.56.1
  - r-biostrings=2.68.1
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0-7
  - r-blob=1.2.4
  - r-brew=1.0-8
  - r-brio=1.1.3
  - r-broom=1.0.6
  - r-broom.helpers=1.16.0
  - r-bsgenome=1.68.0
  - r-bsgenome.hsapiens.ucsc.hg38=1.4.5
  - r-bslib=0.8.0
  - r-cachem=1.1.0
  - r-cairo=1.6-2
  - r-callr=3.7.3
  - r-car=3.1-2
  - r-cardata=3.0-5
  - r-catools=1.18.2
  - r-celldex=1.10.1
  - r-cellranger=1.1.0
  - r-checkmate=2.3.1
  - r-circlize=0.4.16
  - r-classint=0.4-11
  - r-cli=3.6.1
  - r-clipr=0.8.0
  - r-clue=0.3-66
  - r-clusterprofiler=4.8.3
  - r-cner=1.36.0
  - r-collections=0.3.7
  - r-colorspace=2.1-0
  - r-combinat=0.0-8
  - r-commonmark=1.9.0
  - r-complexheatmap=2.18.0
  - r-compquadform=1.4.3
  - r-conflicted=1.2.0
  - r-consensustme=0.0.1.9000
  - r-corrplot=0.92
  - r-cowplot=1.1.1
  - r-cpp11=0.5.1
  - r-crayon=1.5.2
  - r-credentials=2.0.1
  - r-crosstalk=1.2.0
  - r-curl=5.0.1
  - r-cyclocomp=1.1.1
  - r-data.table=1.14.8
  - r-datawizard=0.12.2
  - r-dbi=1.1.3
  - r-dbplyr=2.3.3
  - r-ddrtree=0.1.5
  - r-debugme=1.2.0
  - r-deepsnv=1.46.0
  - r-delayedarray=0.26.6
  - r-delayedmatrixstats=1.22.1
  - r-deldir=1.0-9
  - r-dendextend=1.17.1
  - r-deoptimr=1.1-3
  - r-desc=1.4.2
  - r-deseq2=1.40.2
  - r-devtools=2.4.5
  - r-diffobj=0.3.5
  - r-digest=0.6.33
  - r-dir.expiry=1.8.0
  - r-dirichletmultinomial=1.42.0
  - r-diverse=0.1.5
  - r-dnacopy=1.74.1
  - r-docopt=0.7.1
  - r-doparallel=1.0.17
  - r-dose=3.26.2
  - r-dotcall64=1.2
  - r-downlit=0.4.3
  - r-downloader=0.4
  - r-dplyr=1.1.2
  - r-dqrng=0.3.0
  - r-dt=0.33
  - r-dtplyr=1.3.1
  - r-e1071=1.7-16
  - r-edger=3.42.4
  - r-effectsize=0.8.9
  - r-ellipse=0.5.0
  - r-ellipsis=0.3.2
  - r-emmeans=1.8.8
  - r-enhancedvolcano=1.18.0
  - r-enrichplot=1.20.3
  - r-entropy=1.3.1
  - r-estimability=1.4.1
  - r-europepmc=0.4.3
  - r-evaluate=0.21
  - r-exactranktests=0.8-35
  - r-experimenthub=2.8.1
  - r-factoextra=1.0.7
  - r-factominer=2.9
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastdummies=1.7.4
  - r-fastica=1.2-7
  - r-fastmap=1.2.0
  - r-fastmatch=1.1-3
  - r-fftw=1.0-8
  - r-fgsea=1.26.0
  - r-filelock=1.0.2
  - r-findpython=1.0.8
  - r-fitdistrplus=1.1-11
  - r-flashclust=1.01-2
  - r-fnn=1.1.3.2
  - r-fontawesome=0.5.1
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-formatr=1.14
  - r-formula=1.2-5
  - r-fs=1.6.3
  - r-fst=0.9.8
  - r-fstcore=0.9.18
  - r-furrr=0.3.1
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.33.0
  - r-future.apply=1.11.0
  - r-gargle=1.5.2
  - r-genekitr=1.2.8
  - r-generics=0.1.3
  - r-geneset=0.2.7
  - r-genomeinfodb=1.36.1
  - r-genomeinfodbdata=1.2.10
  - r-genomicalignments=1.36.0
  - r-genomicfeatures=1.52.1
  - r-genomicranges=1.52.0
  - r-geoquery=2.68.0
  - r-gert=2.0.0
  - r-getoptlong=1.0.5
  - r-ggally=2.2.1
  - r-ggbeeswarm=0.7.2
  - r-ggeffects=1.7.0
  - r-ggforce=0.4.2
  - r-ggfun=0.1.5
  - r-ggnewscale=0.4.10
  - r-ggokabeito=0.1.0
  - r-ggplot2=3.5.1
  - r-ggplotify=0.1.2
  - r-ggpubr=0.6.0
  - r-ggraph=2.2.1
  - r-ggrastr=1.0.2
  - r-ggrepel=0.9.3
  - r-ggridges=0.5.4
  - r-ggsci=3.0.0
  - r-ggsignif=0.6.4
  - r-ggstats=0.6.0
  - r-ggtext=0.1.2
  - r-ggtree=3.8.2
  - r-ggvenn=0.1.10
  - r-ggvenndiagram=1.5.2
  - r-ggvis=0.4.9
  - r-gh=1.4.0
  - r-gitcreds=0.1.2
  - r-glmnet=4.1-8
  - r-globaloptions=0.1.2
  - r-globals=0.16.2
  - r-glue=1.6.2
  - r-go.db=3.17.0
  - r-goftest=1.2-3
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gosemsim=2.26.1
  - r-gplots=3.1.3
  - r-gprofiler2=0.2.2
  - r-graph=1.78.0
  - r-graphlayouts=1.1.1
  - r-gratia=0.9.2
  - r-gridextra=2.3
  - r-gridgraphics=0.5-1
  - r-gridtext=0.1.5
  - r-grr=0.9.5
  - r-gseabase=1.62.0
  - r-gson=0.1.0
  - r-gsva=1.48.3
  - r-gtable=0.3.3
  - r-gtools=3.9.4
  - r-hardhat=1.4.0
  - r-harmony=1.2.3
  - r-haven=2.5.3
  - r-hdf5array=1.28.1
  - r-hdf5r=1.3.10
  - r-hdo.db=0.99.1
  - r-here=1.0.1
  - r-highr=0.10
  - r-hmisc=5.1-3
  - r-hms=1.1.3
  - r-hsmmsinglecell=1.20.0
  - r-htmltable=2.4.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.2
  - r-httpgd=2.0.2
  - r-httpuv=1.6.11
  - r-httr=1.4.6
  - r-httr2=0.2.3
  - r-ica=1.0-3
  - r-ids=1.0.1
  - r-igraph=1.5.0.1
  - r-ini=0.3.1
  - r-insight=0.20.3
  - r-interactions=1.2.0
  - r-interactivedisplaybase=1.38.0
  - r-iranges=2.34.1
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-janitor=2.2.1
  - r-jpeg=0.1-10
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.7
  - r-jtools=2.2.2
  - r-keggrest=1.40.0
  - r-kernlab=0.9-32
  - r-km.ci=0.5-6
  - r-kmsurv=0.1-5
  - r-knitr=1.43
  - r-labeling=0.4.2
  - r-labelled=2.13.0
  - r-lambda.r=1.2.4
  - r-lamian=0.99.2
  - r-languageserver=0.3.16
  - r-later=1.3.1
  - r-lazyeval=0.2.2
  - r-leaps=3.1
  - r-leiden=0.4.3
  - r-leidenbase=0.1.31
  - r-lifecycle=1.0.3
  - r-limma=3.56.2
  - r-listenv=0.9.0
  - r-lme4=1.1-34
  - r-lmtest=0.9-40
  - r-locfit=1.5-9.8
  - r-lubridate=1.9.2
  - r-maftools=2.16.0
  - r-magrittr=2.0.3
  - r-markdown=1.7
  - r-mathjaxr=1.6-0
  - r-matrix=1.6-0
  - r-matrixcalc=1.0-6
  - r-matrixgenerics=1.12.2
  - r-matrixmodels=0.5-2
  - r-matrixstats=1.0.0
  - r-maxstat=0.7-25
  - r-mclust=6.1.1
  - r-memoise=2.0.1
  - r-meta=7.0-0
  - r-metadat=1.2-0
  - r-metafor=4.6-0
  - r-metap=1.11
  - r-mgcv=1.9-1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-minqa=1.2.5
  - r-mixtools=2.0.0
  - r-mnormt=2.1.1
  - r-modelr=0.1.11
  - r-monocle=2.28.0
  - r-monocle3=1.3.7
  - r-motifmatchr=1.22.0
  - r-msigdbr=7.5.1
  - r-multcomp=1.4-25
  - r-multcompview=0.1-9
  - r-multtest=2.56.0
  - r-munsell=0.5.0
  - r-mutoss=0.1-13
  - r-mvnfast=0.2.8
  - r-mvtnorm=1.2-2
  - r-nloptr=2.0.3
  - r-nortest=1.0-4
  - r-numderiv=2016.8-1.1
  - r-olsrr=0.5.3
  - r-openssl=2.1.0
  - r-openxlsx=4.2.7.1
  - r-org.hs.eg.db=3.17.0
  - r-pander=0.6.5
  - r-parallelly=1.36.0
  - r-parameters=0.22.1
  - r-patchwork=1.3.0
  - r-pbapply=1.7-2
  - r-pbkrtest=0.5.2
  - r-pbmcapply=1.5.1
  - r-performance=0.12.2
  - r-permute=0.9-7
  - r-pheatmap=1.0.12
  - r-phenopath=1.24.0
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.4
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.0.7
  - r-pkgload=1.3.2.1
  - r-plogr=0.2.0
  - r-plotly=4.10.2
  - r-plotrix=3.8-4
  - r-plyr=1.8.8
  - r-png=0.1-8
  - r-polyclip=1.10-4
  - r-polynom=1.4-1
  - r-powerlaw=0.80.0
  - r-ppcor=1.1
  - r-pracma=2.4.4
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-princurve=2.1.6
  - r-proc=1.18.5
  - r-processx=3.8.2
  - r-profvis=0.3.8
  - r-progress=1.2.2
  - r-progressr=0.13.0
  - r-promises=1.2.0.1
  - r-proxy=0.4-27
  - r-ps=1.7.5
  - r-pscl=1.5.9
  - r-purrr=1.0.1
  - r-qlcmatrix=0.9.8
  - r-qqconf=1.3.2
  - r-qs=0.27.2
  - r-quantreg=5.96
  - r-qusage=2.34.0
  - r-qvalue=2.32.0
  - r-r.cache=0.16.0
  - r-r.methodss3=1.8.2
  - r-r.oo=1.25.0
  - r-r.utils=2.12.2
  - r-r6=2.5.1
  - r-ragg=1.2.5
  - r-randomforest=4.7-1.1
  - r-rann=2.6.1
  - r-rapiserialize=0.1.4
  - r-rappdirs=0.3.3
  - r-raster=3.6-23
  - r-rattle=5.5.1
  - r-rbgl=1.76.0
  - r-rbibutils=2.3
  - r-rcistarget=1.20.0
  - r-rcistarget.hg19.motifdbs.cisbponly.500bp=1.20.0
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1-3
  - r-rcpp=1.0.11
  - r-rcppannoy=0.0.21
  - r-rcpparmadillo=0.12.4.1.0
  - r-rcppeigen=0.3.3.9.3
  - r-rcpphnsw=0.6.0
  - r-rcppparallel=5.1.10
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.2
  - r-rcurl=1.98-1.12
  - r-rdpack=2.6.1
  - r-readr=2.1.4
  - r-readxl=1.4.3
  - r-reformulas=0.4.0
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-remotes=2.4.2.1
  - r-reprex=2.0.2
  - r-reshape=0.8.9
  - r-reshape2=1.4.4
  - r-residualmatrix=1.12.0
  - r-restfulr=0.0.15
  - r-reticulate=1.30
  - r-rex=1.2.1
  - r-rhdf5=2.44.0
  - r-rhdf5filters=1.12.1
  - r-rhdf5lib=1.22.0
  - r-rhpcblasctl=0.23-42
  - r-rhtslib=2.2.0
  - r-rjson=0.2.21
  - r-rlang=1.1.1
  - r-rmarkdown=2.23
  - r-robustbase=0.99-4-1
  - r-rocr=1.0-11
  - r-roxygen2=7.2.3
  - r-rpart.plot=3.1.2
  - r-rprojroot=2.0.3
  - r-rsample=1.2.1
  - r-rsamtools=2.16.0
  - r-rselenium=1.7.9
  - r-rspectra=0.16-2
  - r-rsqlite=2.3.1
  - r-rstatix=0.7.2
  - r-rstudioapi=0.15.0
  - r-rsvd=1.0.5
  - r-rtracklayer=1.60.0
  - r-rtsne=0.16
  - r-runit=0.4.33
  - r-rversions=2.1.2
  - r-rvest=1.0.3
  - r-s2=1.1.7
  - r-s4arrays=1.0.4
  - r-s4vectors=0.38.1
  - r-sandwich=3.1-0
  - r-sass=0.4.9
  - r-scaledmatrix=1.8.1
  - r-scales=1.3.0
  - r-scattermore=1.2
  - r-scatterpie=0.2.3
  - r-scatterplot3d=0.3-44
  - r-sccatch=3.2.2
  - r-scgate=1.6.2
  - r-sctransform=0.3.5
  - r-scuttle=1.12.0
  - r-segmented=1.6-4
  - r-selectr=0.4-2
  - r-semver=0.2.0
  - r-seqlogo=1.66.0
  - r-sessioninfo=1.2.2
  - r-seurat=4.3.0.1
  - r-seuratdisk=0.0.0.9021
  - r-seuratobject=4.1.3
  - r-sf=1.0-19
  - r-shadowtext=0.1.3
  - r-shape=1.4.6
  - r-shiny=1.9.1
  - r-shinybs=0.61.1
  - r-shinyjs=2.1.0
  - r-shinywidgets=0.8.6
  - r-showimage=1.0.0
  - r-singlecellexperiment=1.22.0
  - r-singler=2.2.0
  - r-singscore=1.20.0
  - r-sitmo=2.0.2
  - r-sjlabelled=1.2.0
  - r-sjmisc=2.8.10
  - r-sjplot=2.8.16
  - r-sjstats=0.19.0
  - r-slam=0.1-55
  - r-slider=0.3.2
  - r-slingshot=2.8.0
  - r-sn=2.1.1
  - r-snakecase=0.11.1
  - r-snow=0.4-4
  - r-sourcetools=0.1.7-1
  - r-sp=2.0-0
  - r-spam=2.11-0
  - r-sparsearray=1.2.4
  - r-sparsem=1.81
  - r-sparsematrixstats=1.12.2
  - r-sparsesvd=0.2-2
  - r-spatstat.data=3.0-1
  - r-spatstat.explore=3.2-1
  - r-spatstat.geom=3.2-4
  - r-spatstat.random=3.1-5
  - r-spatstat.sparse=3.0-2
  - r-spatstat.univar=3.1-1
  - r-spatstat.utils=3.0-3
  - r-spdata=2.3.4
  - r-spdep=1.3-10
  - r-speedglm=0.3-5
  - r-stacas=2.2.2
  - r-statmod=1.5.0
  - r-stringfish=0.16.0
  - r-stringi=1.7.12
  - r-stringr=1.5.0
  - r-styler=1.10.3
  - r-summarizedexperiment=1.30.2
  - r-survminer=0.4.9
  - r-survmisc=0.5.6
  - r-sys=3.4.2
  - r-systemfonts=1.0.4
  - r-tensor=1.5
  - r-terra=1.7-39
  - r-testthat=3.1.10
  - r-textshaping=0.3.6
  - r-tfbstools=1.38.0
  - r-tfisher=0.2.0
  - r-tfmpvalue=0.0.9
  - r-th.data=1.1-2
  - r-tibble=3.2.1
  - r-tidygraph=1.3.1
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-tidytree=0.4.6
  - r-tidyverse=2.0.0
  - r-timechange=0.2.0
  - r-tinytex=0.45
  - r-topgo=2.54.0
  - r-tradeseq=1.14.0
  - r-trajectoryutils=1.8.0
  - r-treeio=1.24.3
  - r-triebeard=0.4.1
  - r-tscan=2.0.0
  - r-tweenr=2.0.3
  - r-tximport=1.28.0
  - r-tzdb=0.4.0
  - r-ucell=2.6.2
  - r-umap=0.2.10.0
  - r-unigd=0.1.2
  - r-units=0.8-5
  - r-urlchecker=1.0.1
  - r-urltools=1.7.3
  - r-usethis=2.2.2
  - r-utf8=1.2.3
  - r-uuid=1.1-0
  - r-uwot=0.1.16
  - r-variantannotation=1.46.0
  - r-vctrs=0.6.3
  - r-vegan=2.6-8
  - r-venn=1.12
  - r-venndiagram=1.7.3
  - r-vgam=1.1-8
  - r-vipor=0.4.7
  - r-viridis=0.6.4
  - r-viridislite=0.4.2
  - r-visnetwork=2.1.2
  - r-vroom=1.6.3
  - r-waldo=0.5.1
  - r-warp=0.2.1
  - r-waterfall=1.0.2
  - r-wdman=0.2.6
  - r-webdriver=1.0.6
  - r-whisker=0.4.1
  - r-withr=2.5.0
  - r-wk=0.9.4
  - r-writexl=1.5.0
  - r-xfun=0.39
  - r-xml=3.99-0.14
  - r-xml2=1.3.5
  - r-xmlparsedata=1.0.5
  - r-xopen=1.0.0
  - r-xtable=1.8-4
  - r-xvector=0.40.0
  - r-yaml=2.3.7
  - r-yardstick=1.3.1
  - r-yulab.utils=0.1.4
  - r-zellkonverter=1.10.1
  - r-zip=2.3.0
  - r-zlibbioc=1.46.0
  - r-zoo=1.8-12
  - r-boot=1.3-28.1
  - r-class=7.3-22
  - r-cluster=2.1.4
  - r-codetools=0.2-19
  - r-foreign=0.8-84
  - r-kernsmooth=2.23-21
  - r-lattice=0.21-8
  - r-mass=7.3-60
  - r-matrix=1.5-4.1
  - r-mgcv=1.8-42
  - r-nlme=3.1-162
  - r-nnet=7.3-19
  - r-rpart=4.1.19
  - r-spatial=7.3-16
  - r-survival=3.5-5
  - r-translations=4.3.1
